# docker-compose.yml (Final Fix)
# This version matches the working architecture from your capstone project.

services:
  # 1. Nginx Proxy Service
  proxy:
    image: nginx:alpine
    container_name: stock_proxy
    ports:
      - "8000:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

  # 2. Database Service
  db:
    image: postgres:14-alpine
    container_name: stock_db
    restart: always
    environment:
      - POSTGRES_DB=stock_management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database-schema.sql:/docker-entrypoint-initdb.d/init.sql

  # 3. Backend Service
  backend:
    container_name: stock_backend
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=db
      - DB_NAME=stock_management
      - DB_USER=postgres
      - DB_PASS=password
      - FLASK_ENV=development
    depends_on:
      - db

  # 4. Frontend Service
  frontend:
    container_name: stock_frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=/api
    depends_on:
      - backend

volumes:
  postgres_data:
